### ISSUE TITLE
Improve `begin domains list`

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#160]
When I do a `begin domains list` I get:

```
https://enhance-movies.com
 └── enhance-movie: "production"
https://enhance-movie.com
 └── enhance-movie: "production"
```

Which is useful but I'd love to see the app ID and env ID in this listing.

**Comment by tbeseda** [comment]
**More detail is provided with the `-v` flag.** 

No domain operations require an ID, they all prompt for things like App and Env with a list of available items.

Eventually it would be nice to eliminate the need for any ID in any command.

I'm conflicted because a user isn't likely to have a huge list of domains so there is "room" to show an ID for each. On the other hand, even short IDs aren't very usable by humans.
