### ISSUE TITLE
begin deploy does not deploy env variables set by plugins

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#70]
Begin deploy does not deploy environment variables set by plugins

**Comment by ryanblock** [comment]
Ok, I can see the issue and have it isolated. Fixing it is going to be a bit trickier, however. Please stand by!

**Comment by ryanblock** [comment]
Ok, I think this is going to have to remain an open issue for a little while. It can be partially worked around, but only partly. Begin enables folks to use arbitrary "environment" names different from Architect's concepts of environments; the Arc apps that Begin deploys are all `staging` right now. We'll prob want to bring this stuff into line at some point in the future, but until then this particular API is not going to work in Begin.

**Comment by ryanblock** [comment]
I considered this further, and it strikes me as being better to support the `set.env` API with Begin-specific caveats rather than not support it at all, I think?

So as of now, if you use non-environment-specific env vars, it'll work, as in below:
```
module.exports = {
  set: {
    env: () => {
      return {
        OH_NOES: 'OH YES!'
      }
    }
  }
}
```

However, if you were to `return { production }`, that is not currently going to work in Begin for the aforementioned reasons.
